name: Go Vet

on:
  push:
    branches:
      - master
    paths-ignore:
      - 'docs/**'
      - '**/*.md'
  pull_request:
    branches:
      - master
    paths-ignore:
      - 'docs/**'
      - '**/*.md'

jobs:
  static-analysis:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.19'

      - name: Cache Go modules
        uses: actions/cache@v3
        with:
          path: |
            ~/.cache/go-build
            ~/go/pkg/mod
          key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            ${{ runner.os }}-go-

      - name: Install Dependencies
        run: go mod download

      - name: Run Go Vet
        run: go vet ./...